AllCops:
  Exclude:
    - 'Rakefile'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/bundle'
    - db/schema.rb

  NewCops: enable
  TargetRubyVersion: 3.1.4
  UseCache: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
